### ISSUE TITLE
无效的玩家数据

### ISSUE THREAD

**Issue by WGTKS** [XiaoHuNao/EnemyBanner#2]
[2024-04-22-7.log](https://github.com/XiaoHuNao/EnemyBanner/files/15055850/2024-04-22-7.log)

**Comment by WGTKS** [comment]
进旧世界还是创建新世界都显示连接已丢失 无效的玩家数据

**Comment by XiaoHuNao** [comment]
请联系我2250529589

**Comment by XiaoHuNao** [comment]
I have tried to fix, please update 0.0.4 version
